[package]
name = "crustls"
version = "0.1.0"
authors = ["Jacob Hoffman-Andrews <github@hoffman-andrews.com>"]

[dependencies]
rustls = "0.19"
webpki = "0.21"
libc = "0.2.81"

[dev_devpendencies]
cbindgen = "*"

[lib]
name = "crustls"
crate-type = ["staticlib"]
